### ISSUE TITLE
Document how to change background color

### ISSUE THREAD

**Issue by remorses** [rpearce/react-medium-image-zoom#333]
In v4 you could use the `overlayBgColorStart` props to change background color, now you can use the following css (in this case i am also changing background when in dark mode)

```css
[data-rmiz-modal-overlay='hidden'] {˙
    background-color: rgba(255, 255, 255, 0);
}
[data-rmiz-modal-overlay='visible'] {
    background-color: rgba(255, 255, 255, 0.6);
    backdrop-filter: saturate(180%) blur(60px);
    -webkit-backdrop-filter: saturate(180%) blur(60px);
}
.dark [data-rmiz-modal-overlay='hidden'] {
    background-color: rgba(0, 0, 0, 0);
}
.dark [data-rmiz-modal-overlay='visible'] {
    background-color: rgba(0, 0, 0, 0.6);
}
```
