### ISSUE TITLE
Hide minimize button

### ISSUE THREAD

**Issue by 1mehdifaraji** [rpearce/react-medium-image-zoom#552]
## Issue Type

- [ ] Bug report
- [*] Feature request
- [ ] Question / support request
- [ ] Other

## Description

Can't find a prop for the `<Zoom></Zoom>` element to hide the Minimize button when an image is clicked. I had to add a custom css style to hide it.

```css
/* React medium zoom image */
button[aria-label="Minimize image"] {
  display: none !important;
}
```
